"""Pydantic schemas for the legal agent system."""

from typing import Any, Dict, List, Literal, Optional, Tuple, Union
from datetime import datetime

import pytz
from pydantic import BaseModel, Field, validator


class Evidence(BaseModel):
    """Sentence-span evidence supporting an extracted value."""

    source_document_id: str = Field(
        ...,
        description="Stable document ID from list_documents",
    )
    start_sentence: int = Field(
        ...,
        ge=1,
        description="Inclusive starting sentence ID (1-indexed)",
    )
    end_sentence: int = Field(
        ...,
        ge=1,
        description="Inclusive ending sentence ID (1-indexed)",
    )

    @validator("end_sentence")
    def validate_sentence_range(cls, v, values):
        start_sentence = values.get("start_sentence")
        if start_sentence is not None and v < start_sentence:
            raise ValueError("end_sentence must be >= start_sentence")
        return v


class ExtractedItem(BaseModel):
    """A single extracted value with its supporting evidence."""
    evidence: List[Evidence]
    value: str = Field(..., description="The extracted information from the evidence")
    
    @validator('evidence')
    def validate_has_evidence(cls, v):
        if not v:
            raise ValueError('ExtractedItem must have at least one evidence')
        return v


class ChecklistItem(BaseModel):
    """A single checklist item with its extracted values."""
    key: str
    extracted: List[ExtractedItem] = []
    last_updated: datetime = Field(default_factory=lambda: datetime.now(pytz.timezone('America/New_York')))


class DocumentCoverage(BaseModel):
    """Tracks sentence coverage of a document."""

    windows_read: int = 0
    approx_sentences_read: int = 0
    sentence_ranges: List[Tuple[int, int]] = Field(
        default_factory=list,
        description="List of (start, end) inclusive sentence ranges viewed",
    )


class DocumentReadInfo(BaseModel):
    """Last read position in a document."""

    start_sentence: int
    end_sentence: int


class DocumentInfo(BaseModel):
    """Information about a document in the corpus."""

    doc_id: str
    type: str  # Flexible string type instead of enum
    sentence_count: int
    visited: bool = False
    coverage: DocumentCoverage = Field(default_factory=DocumentCoverage)
    last_read: Optional[DocumentReadInfo] = None


class ActionRecord(BaseModel):
    """Record of an action taken by the orchestrator."""
    tool: str
    target: Dict[str, Any]
    step: int  # The actual step number when this action was taken
    purpose: Optional[str] = None
    changed_keys: List[str] = []
    timestamp: datetime = Field(default_factory=lambda: datetime.now(pytz.timezone('America/New_York')))
    success: bool = True  # Whether the action succeeded
    error: Optional[str] = None  # Error message if action failed
    validation_errors: List[str] = []  # Business logic errors from tool output
    result_summary: Optional[Dict[str, Any]] = None  # Store tool result for formatting
    auto_generated: bool = False  # Whether this action was auto-generated by the system


class RunHeader(BaseModel):
    """Metadata for a run."""
    run_id: str
    step: int
    timestamp: datetime = Field(default_factory=lambda: datetime.now(pytz.timezone('America/New_York')))


class Task(BaseModel):
    """Task specification."""
    user_instruction: str = Field(..., description="What the user wants the agent to do")
    constraints: List[str] = Field(default_factory=list, description="Optional task-specific constraints beyond system prompt")
    checklist_definitions: Dict[str, str] = Field(default_factory=dict, description="Definitions of checklist items to extract")
    focus_context: Optional[str] = Field(
        default=None,
        description="Optional focus context describing the target matter and exclusion boundaries",
    )


class DerivedStateEntry(BaseModel):
    """One persisted derived-state entry."""

    id: str
    text: str
    source_document_ids: List[str] = Field(
        default_factory=list,
        description="Optional supporting document IDs that ground this entry",
    )
    pinned: bool = Field(
        default=True,
        description="Pinned entries are injected into the prompt; unpinned entries are hidden context",
    )
    last_updated: datetime = Field(default_factory=lambda: datetime.now(pytz.timezone('America/New_York')))


class DerivedState(BaseModel):
    """Persistent derived state memory board."""

    confirmed_state: List[DerivedStateEntry] = Field(default_factory=list)
    open_questions: List[DerivedStateEntry] = Field(default_factory=list)
    external_refs: List[DerivedStateEntry] = Field(default_factory=list)


# ChecklistSummary is deprecated - we now use the full checklist in Snapshot
# and calculate summary statistics on-the-fly in the formatter
# class ChecklistSummary(BaseModel):
#     """Summary of checklist extraction status."""
#     extracted_count: int = Field(..., description="Number of keys with at least one extracted value")
#     empty_count: int = Field(..., description="Number of keys with no extracted values")
#     total_values: int = Field(..., description="Total number of extracted values across all keys")
#     keys_with_values: Dict[str, int] = Field(default_factory=dict, description="Mapping of key to count of extracted values")


class Snapshot(BaseModel):
    """Compact snapshot passed to orchestrator each turn."""
    run_header: RunHeader
    task: Task
    documents: List[DocumentInfo]
    checklist: List[ChecklistItem]  # Full checklist for detailed formatting
    action_tail: List[ActionRecord]
    recent_evidence_headers: List[Evidence]
    last_tool_result: Optional[Dict[str, Any]] = None
    last_tool_name: Optional[str] = None  # Name of the tool that produced last_tool_result
    stop_count: int = 0  # Number of stop attempts
    first_stop_step: Optional[int] = None  # Step number of first stop attempt
    recent_actions_detail: int = 5  # Number of recent actions to show with detailed results
    derived_state: Optional[DerivedState] = None
    derived_state_enabled: bool = False


# Tool I/O schemas

class ListDocumentsOutput(BaseModel):
    """Output of list_documents tool."""
    documents: List[DocumentInfo]


class ReadDocumentInput(BaseModel):
    """Input for read_document tool."""

    doc_id: str
    start_sentence: int = Field(..., ge=1)
    end_sentence: int = Field(..., ge=1)

    @validator("end_sentence")
    def validate_sentence_range(cls, v, values):
        start_sentence = values.get("start_sentence")
        if start_sentence is not None and v < start_sentence:
            raise ValueError("end_sentence must be >= start_sentence")
        return v


class ReadDocumentOutput(BaseModel):
    """Output of read_document tool."""

    doc_id: str
    start_sentence: int
    end_sentence: int
    text: str


class RegexMatch(BaseModel):
    """A single regex match result."""

    start_sentence: int
    end_sentence: int
    start_char: int
    end_char: int
    snippet: str
    groups: Dict[str, str] = {}
    pattern: str
    flags: List[str] = []


class SearchDocumentRegexInput(BaseModel):
    """Input for search_document_regex tool."""

    doc_id: Optional[str] = None  # Single document ID or "all"
    doc_ids: Optional[List[str]] = None  # Array of specific document IDs
    pattern: str
    flags: List[Literal["IGNORECASE", "MULTILINE", "DOTALL"]] = []
    top_k: int = Field(5, ge=1, le=20)

    @validator("doc_id", "doc_ids")
    def validate_at_least_one_doc_specified(cls, v, values):
        """Ensure at least one of doc_id/doc_ids is provided."""
        if "doc_id" not in values and "doc_ids" not in values and v is None:
            raise ValueError("Either doc_id or doc_ids must be provided")
        return v


class DocumentSearchResult(BaseModel):
    """Search results for a single document."""

    doc_id: str
    matches: List[RegexMatch]
    match_count: int


class SearchDocumentRegexOutput(BaseModel):
    """Output of search_document_regex tool."""

    pattern: str
    documents_searched: List[str]  # List of document IDs that were searched
    results: List[DocumentSearchResult]  # Per-document results
    total_matches: int  # Total matches across all documents


class GetChecklistOutput(BaseModel):
    """Output of get_checklist tool."""
    checklist: List[ChecklistItem]
    completion_stats: Dict[str, int] = Field(
        default_factory=lambda: {
            "filled": 0,
            "empty": 0,
            "total": 0  # Will be dynamically set based on checklist configuration
        }
    )


class ChecklistPatch(BaseModel):
    """A patch to update a checklist item."""
    key: str
    extracted: Optional[List[ExtractedItem]] = None
    # Support incremental additions
    add_extracted: Optional[List[ExtractedItem]] = None
    
    @validator('extracted')
    def validate_extracted_has_evidence(cls, v):
        if v is not None:
            for item in v:
                if not item.evidence:
                    raise ValueError('Each extracted item must have at least one evidence')
        return v
    
    @validator('add_extracted')
    def validate_add_extracted_has_evidence(cls, v):
        if v is not None:
            for item in v:
                if not item.evidence:
                    raise ValueError('Each extracted item must have at least one evidence')
        return v


class UpdateChecklistInput(BaseModel):
    """Input for update_checklist tool."""
    patch: List[ChecklistPatch]


class UpdateChecklistOutput(BaseModel):
    """Output of update_checklist tool."""
    updated_keys: List[str]
    validation_errors: List[str] = []
    success: bool


class AppendChecklistOutput(BaseModel):
    """Output of append_checklist tool."""
    appended_keys: List[str]
    items_added: Dict[str, int] = Field(default_factory=dict)
    duplicates_skipped: Dict[str, int] = Field(default_factory=dict)
    validation_errors: List[str] = []
    success: bool


class StopDecision(BaseModel):
    """Stop decision from orchestrator."""
    decision: Literal["stop"]
    reason: str
    remaining_empty_keys: List[str] = []


class OrchestratorAction(BaseModel):
    """Action chosen by orchestrator."""
    tool: Optional[str] = None
    args: Optional[Dict[str, Any]] = None
    decision: Optional[Literal["stop"]] = None
    reason: Optional[str] = None
    remaining_empty_keys: Optional[List[str]] = None
    stats: Optional[Dict[str, Any]] = None  # Token usage statistics
    parse_failed: Optional[bool] = False  # Flag for parse/validation errors
    
    @validator('tool')
    def validate_action_type(cls, v, values):
        # Allow special error actions
        if v in ['parse_error', 'validation_error']:
            return v
        if v is None and values.get('decision') != 'stop':
            raise ValueError('Must specify either tool or decision=stop')
        if v is not None and values.get('decision') == 'stop':
            raise ValueError('Cannot specify both tool and stop decision')
        return v


# Ledger schemas for tracking reads and searches

class ReadEvent(BaseModel):
    """Record of a document read."""

    timestamp: datetime = Field(default_factory=lambda: datetime.now(pytz.timezone('America/New_York')))
    doc_id: str
    start_sentence: int
    end_sentence: int
    sentences_read: int
    step: int


class SearchEvent(BaseModel):
    """Record of a regex search (single or multi-document)."""

    timestamp: datetime = Field(default_factory=lambda: datetime.now(pytz.timezone('America/New_York')))
    # Search specification - exactly one of these will be set.
    doc_id: Optional[str] = None  # Single doc ID or "all"
    doc_ids: Optional[List[str]] = None  # List of specific doc IDs
    pattern: str
    flags: List[str]
    matches_found: int  # Total matches across all docs
    step: int
    # Per-document details (includes docs with 0 matches)
    document_matches: Dict[str, List[Tuple[int, int]]] = Field(
        default_factory=dict,
        description="Map of doc_id to list of (start_sentence, end_sentence) ranges",
    )


class UpdateEvent(BaseModel):
    """Record of a checklist update."""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(pytz.timezone('America/New_York')))
    keys_updated: List[str]
    patch: List[ChecklistPatch]
    step: int
    success: bool


class ToolEvent(BaseModel):
    """Generic tool execution event."""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(pytz.timezone('America/New_York')))
    tool_name: str
    args: Dict[str, Any]
    result: Optional[Dict[str, Any]] = None
    success: bool = True
    step: int


class LedgerEntry(BaseModel):
    """Generic ledger entry."""
    event_name: str  # Changed from event_type to event_name, will be the actual tool name
    event: Union[ReadEvent, SearchEvent, UpdateEvent, ToolEvent]
    run_id: str
    step: int
